# This is a basic workflow to help you get started with Actions

name: Policy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - name: Find and Replace
        uses: bejoistic/str-replace@master
        with:
          find: "00000000-0000-0000-0000-000000000000"
          replace: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          include: "policies/**"

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Manage Azure Policy
        uses: Azure/manage-azure-policy@v0
        with:
          paths: policies/**
          #assignments: assign.*_testRG_*.json # Apply only assignment files that match this pattern
          mode: incremental
